id: PFBCCE3DE
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Rinpoche, Samdong & Vajravallabh Dwivedi
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1992'
  महामायातन्त्रम् [गुणवतिटिकासहितम्]:
    Text Version: Devanagari
    Input Personnel: Rashmi Shakya
    Input Date: '2013'
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T17:00:37.261540'
last_modified_at: '2022-03-08T17:00:37.261551'
